### PR TITLE
chore(deps): update deps and broken setups

### PR DESCRIPTION
**Pull request by chrillep**

### CODE REVIEW

**Comment by chrillep** [comment]
@joedixon duuust in the wind ....

**Comment by joedixon** [comment]
Hey @chrillep - apologies for missing this. This isn't a package I have a huge amount of need for anymore, but this wasn't helped by the fact my notifications were not working on this repo.

The PR title - "i don't know what to call this" - can we basically summarise to a big ol' update of dependencies?

I see some of the commits are quite old. Did this start as a fork you maintained separately?

**Comment by chrillep** [comment]
@joedixon no worries. notifications in github get overwhelming fast. yes and no for deps. it also adds functionality from some of the unmerged PR'S.

but yeah mostly just keeping up with the times. 

It began when we started using laravel-translations and I saw you where taking up development of it again. i tried to install nova-translations. but there where a lot of minor updates/fixes needed to be done, that couldn't be fixed locally. so not to let these fixes die silently in a fork this PR now exists 😊

**Comment by joedixon** [comment]
Thanks for the clarification @chrillep - I need to pull this down and give it a test, but honestly, I'm not sure when I'm going to be able to get round to it.

**Comment by chrillep** [comment]
> Thanks for the clarification @chrillep - I need to pull this down and give it a test, but honestly, I'm not sure when I'm going to be able to get round to it.

i hear u. No stress. where moving to nova 4. so maybe there ill be a PR for that soon aswell ;)

**Pull request closed without merging**
